const ADD_ITEM = "ADD_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM";
const UPDATE_ITEM = "UPDATE_ITEM";
const CLEAR_LIST = "CLEAR_LIST";
const SHOW_ERROR = "SHOW_ERROR";

export {
  ADD_ITEM,
  REMOVE_ITEM,
  UPDATE_ITEM,
  CLEAR_LIST,
  SHOW_ERROR
}
